package com.knowledgeops.shared.domain;

public enum ErrorCode {
  VALIDATION_ERROR,
  BAD_REQUEST,
  AUTHENTICATION_REQUIRED,
  INVALID_CREDENTIALS,
  TOKEN_REVOKED,
  FORBIDDEN,
  RESOURCE_NOT_FOUND,
  EMAIL_CONFLICT,
  STATE_CONFLICT,
  AUTH_DEPENDENCY_UNAVAILABLE,
  INTERNAL_ERROR
}
