package com.knowledgeops.shared.domain;

public enum ErrorCode {
  VALIDATION_ERROR,
  BAD_REQUEST,
  AUTHENTICATION_REQUIRED,
  INVALID_CREDENTIALS,
  TOKEN_REVOKED,
  FORBIDDEN,
  RESOURCE_NOT_FOUND,
  EMAIL_CONFLICT,
  STATE_CONFLICT,
  TICKET_NOT_FOUND,
  TICKET_ACCESS_DENIED,
  INVALID_TICKET_STATUS,
  INVALID_ASSIGNEE,
  TICKET_VERSION_CONFLICT,
  KNOWLEDGE_ARTICLE_NOT_FOUND,
  KNOWLEDGE_DOCUMENT_NOT_FOUND,
  KNOWLEDGE_ACCESS_DENIED,
  UNSUPPORTED_FILE_TYPE,
  FILE_TOO_LARGE,
  FILE_STORAGE_ERROR,
  ARTICLE_VERSION_CONFLICT,
  AUTH_DEPENDENCY_UNAVAILABLE,
  INTERNAL_ERROR
}
