<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Plus, Refresh } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { ticketApi } from '../../api/tickets'; import type { Ticket, TicketPriority, TicketStatus } from '../../types'
import { apiErrorMessage } from '../../utils/errors'; import { formatDate, shortId } from '../../utils/format'
import PageHeading from '../../components/PageHeading.vue'; import StatusPill from '../../components/StatusPill.vue'; import EmptyState from '../../components/EmptyState.vue'

const router=useRouter(); const loading=ref(false); const tickets=ref<Ticket[]>([]); const total=ref(0)
const filters=reactive<{page:number;size:number;status?:TicketStatus;priority?:TicketPriority}>({page:0,size:10})
async function load(){loading.value=true;try{const {data}=await ticketApi.list(filters);tickets.value=data.content;total.value=data.totalElements}catch(e){ElMessage.error(apiErrorMessage(e))}finally{loading.value=false}}
function reset(){filters.status=undefined;filters.priority=undefined;filters.page=0;void load()}
onMounted(load)
</script>
<template><div><PageHeading title="Tickets" description="Track service requests and move work through a clear status flow."><el-button @click="reset"><el-icon><Refresh /></el-icon>Reset</el-button><el-button type="primary" @click="router.push('/tickets/new')"><el-icon><Plus /></el-icon>New ticket</el-button></PageHeading><section class="content-card"><div class="filter-bar"><el-select v-model="filters.status" clearable placeholder="All statuses" @change="filters.page=0;load()"><el-option v-for="item in ['OPEN','IN_PROGRESS','RESOLVED','CLOSED']" :key="item" :label="item.replaceAll('_',' ')" :value="item" /></el-select><el-select v-model="filters.priority" clearable placeholder="All priorities" @change="filters.page=0;load()"><el-option v-for="item in ['LOW','MEDIUM','HIGH','URGENT']" :key="item" :label="item" :value="item" /></el-select><span class="result-count">{{ total }} visible ticket{{ total === 1 ? '' : 's' }}</span></div><el-table v-loading="loading" :data="tickets" class="data-table" @row-click="(row: Ticket)=>router.push(`/tickets/${row.id}`)"><el-table-column label="Ticket" min-width="280"><template #default="{row}"><div class="primary-cell"><strong>{{ row.title }}</strong><code>{{ shortId(row.id) }}</code></div></template></el-table-column><el-table-column label="Status" width="150"><template #default="{row}"><StatusPill :value="row.status" /></template></el-table-column><el-table-column label="Priority" width="120"><template #default="{row}"><StatusPill :value="row.priority" /></template></el-table-column><el-table-column label="Creator" width="140"><template #default="{row}"><code>{{ shortId(row.creatorId) }}</code></template></el-table-column><el-table-column label="Assignee" width="140"><template #default="{row}"><code>{{ shortId(row.assigneeId) }}</code></template></el-table-column><el-table-column label="Updated" width="190"><template #default="{row}">{{ formatDate(row.updatedAt) }}</template></el-table-column><template #empty><EmptyState title="No tickets here" description="Create a ticket or adjust the active filters." /></template></el-table><div class="pagination-row"><el-pagination :current-page="filters.page+1" :page-size="filters.size" :total="total" layout="prev, pager, next" @current-change="(page:number)=>{filters.page=page-1;load()}" /></div></section></div></template>
