<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'
import { ticketApi } from '../../api/tickets'; import type { Ticket, TicketComment, TicketStatus } from '../../types'; import { useAuthStore } from '../../stores/auth'; import { hasAnyPermission, hasPermission } from '../../utils/permissions'; import { apiErrorMessage } from '../../utils/errors'; import { displayLabel, formatDate, shortId } from '../../utils/format'; import StatusPill from '../../components/StatusPill.vue'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const id=route.params.id as string;const ticket=ref<Ticket|null>(null);const comments=ref<TicketComment[]>([]);const loading=ref(true);const busy=ref(false);const comment=ref('');const assigneeId=ref('')
const canComment=computed(()=>hasPermission(auth.user,'ticket.comment.public'));const canAssign=computed(()=>hasAnyPermission(auth.user,['ticket.assign.department','ticket.assign.all']));const canTransition=computed(()=>hasAnyPermission(auth.user,['ticket.transition.assigned','ticket.transition.all']))
const transitions=computed<TicketStatus[]>(()=>({OPEN:['IN_PROGRESS'],IN_PROGRESS:['OPEN','RESOLVED'],RESOLVED:['CLOSED'],CLOSED:[]}[ticket.value?.status||'CLOSED'] as TicketStatus[]))
async function load(){loading.value=true;try{const [detail,items]=await Promise.all([ticketApi.get(id),ticketApi.comments(id)]);ticket.value=detail.data;comments.value=items.data;assigneeId.value=detail.data.assigneeId||''}catch(e){ElMessage.error(apiErrorMessage(e));await router.replace('/tickets')}finally{loading.value=false}}
async function action(run:()=>Promise<{data:Ticket}>,message:string){busy.value=true;try{ticket.value=(await run()).data;ElMessage.success(message)}catch(e){ElMessage.error(apiErrorMessage(e));await load()}finally{busy.value=false}}
async function addComment(){if(!comment.value.trim()||!ticket.value)return;busy.value=true;try{await ticketApi.comment(id,comment.value.trim(),ticket.value.version);comment.value='';ElMessage.success('评论已添加');await load()}catch(e){ElMessage.error(apiErrorMessage(e));await load()}finally{busy.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><button class="back-link" @click="router.push('/tickets')">← 返回工单列表</button><div v-if="ticket" class="detail-layout"><section><div class="detail-hero"><div><div class="detail-meta"><code>{{ ticket.id }}</code><StatusPill :value="ticket.priority" /></div><h2>{{ ticket.title }}</h2><p>{{ ticket.description }}</p></div><StatusPill :value="ticket.status" /></div><div class="content-card"><div class="card-heading"><div><span class="eyebrow">协作记录</span><h3>评论</h3></div><span class="result-count">共 {{ comments.length }} 条</span></div><div v-if="comments.length" class="comment-list"><article v-for="item in comments" :key="item.id"><div class="comment-avatar">{{ item.authorId.slice(0,2).toUpperCase() }}</div><div><div class="comment-head"><code>{{ shortId(item.authorId) }}</code><time>{{ formatDate(item.createdAt) }}</time></div><p>{{ item.content }}</p></div></article></div><div v-else class="inline-empty">暂无评论。</div><div v-if="canComment" class="comment-form"><el-input v-model="comment" type="textarea" :rows="3" maxlength="4000" placeholder="补充处理进展…" /><el-button type="primary" :disabled="!comment.trim()" :loading="busy" @click="addComment">添加评论</el-button></div></div></section><aside class="detail-sidebar"><section class="content-card"><span class="eyebrow">工单详情</span><dl class="metadata-list"><div><dt>创建人</dt><dd><code>{{ shortId(ticket.creatorId) }}</code></dd></div><div><dt>处理人</dt><dd><code>{{ shortId(ticket.assigneeId) }}</code></dd></div><div><dt>创建时间</dt><dd>{{ formatDate(ticket.createdAt) }}</dd></div><div><dt>更新时间</dt><dd>{{ formatDate(ticket.updatedAt) }}</dd></div><div><dt>版本</dt><dd>{{ ticket.version }}</dd></div></dl></section><section v-if="canAssign||canTransition" class="content-card action-card"><span class="eyebrow">工单操作</span><div v-if="canAssign" class="side-action"><label>分配支持人员</label><el-input v-model="assigneeId" placeholder="支持人员 UUID" /><el-button :loading="busy" @click="action(()=>ticketApi.assign(id,assigneeId,ticket!.version),'工单已分配')">分配</el-button></div><div v-if="canTransition&&transitions.length" class="side-action"><label>变更状态</label><el-button v-for="status in transitions" :key="status" :loading="busy" type="primary" plain @click="action(()=>ticketApi.transition(id,status,ticket!.version),`工单已转为${displayLabel(status)}`)">{{ displayLabel(status) }}</el-button></div></section></aside></div></div></template>
