<script setup lang="ts">
import { reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { ticketApi } from '../../api/tickets'; import type { TicketPriority } from '../../types'; import { apiErrorMessage } from '../../utils/errors'; import PageHeading from '../../components/PageHeading.vue'
const router=useRouter(); const saving=ref(false); const formRef=ref<FormInstance>()
const form=reactive<{title:string;description:string;priority:TicketPriority}>({title:'',description:'',priority:'MEDIUM'})
const rules:FormRules={title:[{required:true,message:'Enter a title',trigger:'blur'},{max:200,message:'Use 200 characters or fewer',trigger:'blur'}],description:[{required:true,message:'Describe the issue',trigger:'blur'},{max:10000,message:'Description is too long',trigger:'blur'}],priority:[{required:true}]}
async function save(){if(!await formRef.value?.validate().catch(()=>false))return;saving.value=true;try{const {data}=await ticketApi.create(form);ElMessage.success('Ticket created');await router.replace(`/tickets/${data.id}`)}catch(e){ElMessage.error(apiErrorMessage(e))}finally{saving.value=false}}
</script>
<template><div class="narrow-page"><PageHeading title="Create ticket" description="Give the service team enough context to act quickly." /><section class="content-card form-card"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="Title" prop="title"><el-input v-model="form.title" size="large" maxlength="200" show-word-limit placeholder="A short summary of the request" /></el-form-item><el-form-item label="Priority" prop="priority"><el-segmented v-model="form.priority" :options="['LOW','MEDIUM','HIGH','URGENT']" /></el-form-item><el-form-item label="Description" prop="description"><el-input v-model="form.description" type="textarea" :rows="9" maxlength="10000" show-word-limit placeholder="What happened, what did you expect, and what have you tried?" /></el-form-item><div class="form-actions"><el-button @click="router.back()">Cancel</el-button><el-button type="primary" :loading="saving" @click="save">Create ticket</el-button></div></el-form></section></div></template>
