<script setup lang="ts">
import { reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { ticketApi } from '../../api/tickets'; import type { TicketPriority } from '../../types'; import { apiErrorMessage } from '../../utils/errors'; import PageHeading from '../../components/PageHeading.vue'
const router=useRouter(); const saving=ref(false); const formRef=ref<FormInstance>()
const form=reactive<{title:string;description:string;priority:TicketPriority}>({title:'',description:'',priority:'MEDIUM'})
const priorityOptions=[{label:'低',value:'LOW'},{label:'中',value:'MEDIUM'},{label:'高',value:'HIGH'},{label:'紧急',value:'URGENT'}]
const rules:FormRules={title:[{required:true,message:'请输入标题',trigger:'blur'},{max:200,message:'标题不能超过 200 个字符',trigger:'blur'}],description:[{required:true,message:'请描述问题',trigger:'blur'},{max:10000,message:'问题描述不能超过 10000 个字符',trigger:'blur'}],priority:[{required:true,message:'请选择优先级'}]}
async function save(){if(!await formRef.value?.validate().catch(()=>false))return;saving.value=true;try{const {data}=await ticketApi.create(form);ElMessage.success('工单已创建');await router.replace(`/tickets/${data.id}`)}catch(e){ElMessage.error(apiErrorMessage(e))}finally{saving.value=false}}
</script>
<template><div class="narrow-page"><PageHeading title="新建工单" description="请提供足够的信息，帮助支持人员快速处理。" /><section class="content-card form-card"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="标题" prop="title"><el-input v-model="form.title" size="large" maxlength="200" show-word-limit placeholder="简要说明本次请求" /></el-form-item><el-form-item label="优先级" prop="priority"><el-segmented v-model="form.priority" :options="priorityOptions" /></el-form-item><el-form-item label="问题描述" prop="description"><el-input v-model="form.description" type="textarea" :rows="9" maxlength="10000" show-word-limit placeholder="请说明发生了什么、预期结果以及已经尝试过的操作。" /></el-form-item><div class="form-actions"><el-button @click="router.back()">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建工单</el-button></div></el-form></section></div></template>
