package com.knowledgeops.audit.domain;

public enum AuditAction {
  BOOTSTRAP_ADMIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REFRESH,
  REFRESH_REPLAY,
  LOGOUT,
  USER_CREATE,
  USER_DISABLE,
  ROLE_ASSIGN,
  PERMISSION_CHANGE,
  TICKET_CREATED,
  TICKET_ASSIGNED,
  TICKET_STATUS_CHANGED,
  TICKET_COMMENT_ADDED,
  KNOWLEDGE_ARTICLE_CREATED,
  KNOWLEDGE_ARTICLE_UPDATED,
  KNOWLEDGE_ARTICLE_PUBLISHED,
  KNOWLEDGE_ARTICLE_ARCHIVED,
  KNOWLEDGE_DOCUMENT_UPLOADED,
  KNOWLEDGE_DOCUMENT_DOWNLOADED,
  KNOWLEDGE_DOCUMENT_ARCHIVED
}
