<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight } from '@element-plus/icons-vue'
import { ticketApi } from '../../api/tickets'; import { knowledgeApi } from '../../api/knowledge'
import { useAuthStore } from '../../stores/auth'; import { canManageKnowledge } from '../../utils/permissions'

const auth=useAuthStore(); const router=useRouter(); const counts=ref({tickets:0,articles:0,documents:0}); const loading=ref(true)
onMounted(async()=>{const [t,a,d]=await Promise.allSettled([ticketApi.list({page:0,size:1}),knowledgeApi.articles({page:0,size:1}),knowledgeApi.documents({page:0,size:1})]); counts.value={tickets:t.status==='fulfilled'?t.value.data.totalElements:0,articles:a.status==='fulfilled'?a.value.data.totalElements:0,documents:d.status==='fulfilled'?d.value.data.totalElements:0};loading.value=false})
</script>
<template><div><div class="welcome-banner"><div><span class="eyebrow light">Workspace overview</span><h2>Good to see you, {{ auth.user?.displayName.split(' ')[0] }}.</h2><p>Here is what is available in your operations workspace today.</p></div><div class="welcome-orbit"><span>K</span></div></div><div class="metric-grid" v-loading="loading"><div class="metric-card"><span class="metric-label">Visible tickets</span><strong>{{ counts.tickets }}</strong><button @click="router.push('/tickets')">Open queue <el-icon><ArrowRight /></el-icon></button></div><div class="metric-card"><span class="metric-label">Knowledge articles</span><strong>{{ counts.articles }}</strong><button @click="router.push('/knowledge/articles')">Browse library <el-icon><ArrowRight /></el-icon></button></div><div class="metric-card"><span class="metric-label">Available documents</span><strong>{{ counts.documents }}</strong><button @click="router.push('/documents')">View files <el-icon><ArrowRight /></el-icon></button></div></div><div class="dashboard-grid"><section class="content-card"><div class="card-heading"><div><span class="eyebrow">Quick actions</span><h3>Continue your work</h3></div></div><div class="quick-list"><button @click="router.push('/tickets/new')"><span class="quick-icon">＋</span><div><strong>Create a ticket</strong><small>Report a service request or issue</small></div><el-icon><ArrowRight /></el-icon></button><button v-if="canManageKnowledge(auth.user)" @click="router.push('/knowledge/articles/new')"><span class="quick-icon">✦</span><div><strong>Draft an article</strong><small>Turn useful context into guidance</small></div><el-icon><ArrowRight /></el-icon></button><button @click="router.push('/documents')"><span class="quick-icon">⇩</span><div><strong>Find a document</strong><small>Download an approved resource</small></div><el-icon><ArrowRight /></el-icon></button></div></section><section class="content-card identity-card"><span class="eyebrow">Your access</span><h3>{{ auth.user?.roles.join(' · ').replaceAll('_',' ') }}</h3><p>{{ auth.user?.email }}</p><div class="permission-list"><span v-for="permission in auth.user?.permissions" :key="permission">{{ permission }}</span></div></section></div></div></template>
