<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowRight } from '@element-plus/icons-vue'
import { ticketApi } from '../../api/tickets'; import { knowledgeApi } from '../../api/knowledge'
import { useAuthStore } from '../../stores/auth'; import { canManageKnowledge } from '../../utils/permissions'
import { displayLabel } from '../../utils/format'

const auth=useAuthStore(); const router=useRouter(); const counts=ref({tickets:0,articles:0,documents:0}); const loading=ref(true)
onMounted(async()=>{const [t,a,d]=await Promise.allSettled([ticketApi.list({page:0,size:1}),knowledgeApi.articles({page:0,size:1}),knowledgeApi.documents({page:0,size:1})]); counts.value={tickets:t.status==='fulfilled'?t.value.data.totalElements:0,articles:a.status==='fulfilled'?a.value.data.totalElements:0,documents:d.status==='fulfilled'?d.value.data.totalElements:0};loading.value=false})
</script>
<template><div><div class="welcome-banner"><div><span class="eyebrow light">工作空间概览</span><h2>{{ auth.user?.displayName }}，欢迎回来。</h2><p>查看今天可以处理的工单、知识文章和文档。</p></div><div class="welcome-orbit"><span>K</span></div></div><div class="metric-grid" v-loading="loading"><div class="metric-card"><span class="metric-label">可见工单</span><strong>{{ counts.tickets }}</strong><button @click="router.push('/tickets')">查看工单 <el-icon><ArrowRight /></el-icon></button></div><div class="metric-card"><span class="metric-label">知识文章</span><strong>{{ counts.articles }}</strong><button @click="router.push('/knowledge/articles')">浏览知识库 <el-icon><ArrowRight /></el-icon></button></div><div class="metric-card"><span class="metric-label">可用文档</span><strong>{{ counts.documents }}</strong><button @click="router.push('/documents')">查看文档 <el-icon><ArrowRight /></el-icon></button></div></div><div class="dashboard-grid"><section class="content-card"><div class="card-heading"><div><span class="eyebrow">快捷操作</span><h3>继续处理工作</h3></div></div><div class="quick-list"><button @click="router.push('/tickets/new')"><span class="quick-icon">＋</span><div><strong>新建工单</strong><small>提交服务请求或问题</small></div><el-icon><ArrowRight /></el-icon></button><button v-if="canManageKnowledge(auth.user)" @click="router.push('/knowledge/articles/new')"><span class="quick-icon">✦</span><div><strong>起草文章</strong><small>将有用经验整理为知识</small></div><el-icon><ArrowRight /></el-icon></button><button @click="router.push('/documents')"><span class="quick-icon">⇩</span><div><strong>查找文档</strong><small>下载已审核的资料</small></div><el-icon><ArrowRight /></el-icon></button></div></section><section class="content-card identity-card"><span class="eyebrow">我的权限</span><h3>{{ auth.user?.roles.map(displayLabel).join(' · ') }}</h3><p>{{ auth.user?.email }}</p><div class="permission-list"><span v-for="permission in auth.user?.permissions" :key="permission">{{ displayLabel(permission) }}</span></div></section></div></div></template>
