-- Architecture draft; MySQL 8.4 / InnoDB / utf8mb4. NOT an applied migration.
-- UUIDs are generated by the application. All timestamps are UTC DATETIME(6).
-- All FK delete rules default to RESTRICT. Append-only records have no updated_at.
SET NAMES utf8mb4;

CREATE TABLE departments (
 id CHAR(36) PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE users (
 id CHAR(36) PRIMARY KEY, department_id CHAR(36) NOT NULL,
 username VARCHAR(64) NOT NULL UNIQUE, display_name VARCHAR(100) NOT NULL,
 password_hash VARCHAR(255) NOT NULL, status VARCHAR(16) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (department_id) REFERENCES departments(id),
 CONSTRAINT ck_user_status CHECK (status IN ('ACTIVE','DISABLED')),
 INDEX ix_users_department (department_id,status,id)
) ENGINE=InnoDB;

CREATE TABLE roles (
 id CHAR(36) PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(80) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE permissions (
 id CHAR(36) PRIMARY KEY, code VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE user_roles (
 user_id CHAR(36) NOT NULL, role_id CHAR(36) NOT NULL,
 PRIMARY KEY (user_id,role_id), FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (role_id) REFERENCES roles(id)
) ENGINE=InnoDB;
CREATE TABLE role_permissions (
 role_id CHAR(36) NOT NULL, permission_id CHAR(36) NOT NULL,
 PRIMARY KEY (role_id,permission_id), FOREIGN KEY (role_id) REFERENCES roles(id),
 FOREIGN KEY (permission_id) REFERENCES permissions(id)
) ENGINE=InnoDB;
CREATE TABLE security_state (
 id TINYINT PRIMARY KEY, epoch BIGINT NOT NULL, updated_at DATETIME(6) NOT NULL,
 CONSTRAINT ck_security_singleton CHECK (id=1)
) ENGINE=InnoDB;

CREATE TABLE refresh_tokens (
 id CHAR(36) PRIMARY KEY, user_id CHAR(36) NOT NULL, family_id CHAR(36) NOT NULL,
 token_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 expires_at DATETIME(6) NOT NULL, consumed_at DATETIME(6), revoked_at DATETIME(6),
 created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id), INDEX ix_refresh_family (family_id,revoked_at),
 INDEX ix_refresh_user (user_id,revoked_at), INDEX ix_refresh_expiry (expires_at)
) ENGINE=InnoDB;

CREATE TABLE knowledge_bases (
 id CHAR(36) PRIMARY KEY, name VARCHAR(120) NOT NULL, description VARCHAR(1000) NOT NULL,
 status VARCHAR(16) NOT NULL, created_by CHAR(36) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (created_by) REFERENCES users(id), CONSTRAINT ck_kb_status CHECK (status IN ('ACTIVE','ARCHIVED'))
) ENGINE=InnoDB;
CREATE TABLE knowledge_base_members (
 knowledge_base_id CHAR(36) NOT NULL, user_id CHAR(36) NOT NULL, access_level VARCHAR(16) NOT NULL,
 granted_by CHAR(36) NOT NULL, created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 PRIMARY KEY (knowledge_base_id,user_id),
 FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id), FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (granted_by) REFERENCES users(id), CONSTRAINT ck_kb_access CHECK (access_level IN ('READER','MANAGER')),
 INDEX ix_kb_member_user (user_id,knowledge_base_id)
) ENGINE=InnoDB;
CREATE TABLE documents (
 id CHAR(36) PRIMARY KEY, knowledge_base_id CHAR(36) NOT NULL, title VARCHAR(200) NOT NULL,
 status VARCHAR(16) NOT NULL, current_version_id CHAR(36), created_by CHAR(36) NOT NULL,
 version BIGINT NOT NULL DEFAULT 0, archived_at DATETIME(6),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (knowledge_base_id) REFERENCES knowledge_bases(id), FOREIGN KEY (created_by) REFERENCES users(id),
 CONSTRAINT ck_document_status CHECK (status IN ('ACTIVE','ARCHIVED')),
 INDEX ix_document_kb (knowledge_base_id,status,updated_at,id)
) ENGINE=InnoDB;
CREATE TABLE document_versions (
 id CHAR(36) PRIMARY KEY, document_id CHAR(36) NOT NULL, version_no INT NOT NULL,
 source_name VARCHAR(255) NOT NULL, storage_key VARCHAR(255) NOT NULL UNIQUE,
 media_type VARCHAR(100) NOT NULL, size_bytes BIGINT NOT NULL, source_sha256 CHAR(64) NOT NULL,
 status VARCHAR(16) NOT NULL, index_generation CHAR(36),
 parser_revision VARCHAR(100), chunker_revision VARCHAR(100), embedding_revision VARCHAR(200),
 error_code VARCHAR(80), error_message VARCHAR(500), created_by CHAR(36) NOT NULL,
 ready_at DATETIME(6), created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (document_id) REFERENCES documents(id), FOREIGN KEY (created_by) REFERENCES users(id),
 UNIQUE (document_id,version_no), UNIQUE (document_id,id),
 CONSTRAINT ck_version_status CHECK (status IN ('UPLOADED','PROCESSING','READY','FAILED')),
 CONSTRAINT ck_source_size CHECK (size_bytes>0 AND size_bytes<=20971520),
 CONSTRAINT ck_version_number CHECK (version_no>0)
) ENGINE=InnoDB;
-- Composite FK ensures the current version belongs to this document.
ALTER TABLE documents ADD CONSTRAINT fk_document_current_version
 FOREIGN KEY (id,current_version_id) REFERENCES document_versions(document_id,id);

CREATE TABLE document_chunks (
 id CHAR(36) PRIMARY KEY, version_id CHAR(36) NOT NULL, ordinal INT NOT NULL,
 index_generation CHAR(36) NOT NULL, text MEDIUMTEXT NOT NULL, text_sha256 CHAR(64) NOT NULL,
 token_count INT NOT NULL, page_start INT, page_end INT, heading_path VARCHAR(1000),
 char_start INT NOT NULL, char_end INT NOT NULL, created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (version_id) REFERENCES document_versions(id), UNIQUE (version_id,ordinal),
 CONSTRAINT ck_chunk_offsets CHECK (char_start>=0 AND char_end>char_start),
 CONSTRAINT ck_chunk_pages CHECK (page_start IS NULL OR (page_start>0 AND page_end>=page_start))
) ENGINE=InnoDB;
CREATE TABLE document_jobs (
 id CHAR(36) PRIMARY KEY, version_id CHAR(36) NOT NULL, status VARCHAR(16) NOT NULL,
 step VARCHAR(24) NOT NULL, attempts INT NOT NULL DEFAULT 0, available_at DATETIME(6) NOT NULL,
 lease_until DATETIME(6), lease_token CHAR(36), error_code VARCHAR(80),
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (version_id) REFERENCES document_versions(id), INDEX ix_job_queue (status,available_at,id),
 INDEX ix_job_lease (status,lease_until), INDEX ix_job_version (version_id,created_at),
 CONSTRAINT ck_job_status CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED')),
 CONSTRAINT ck_job_step CHECK (step IN ('VALIDATE','PARSE','NORMALIZE','CHUNK','EMBED','INDEX','COMMIT'))
) ENGINE=InnoDB;

CREATE TABLE tickets (
 id CHAR(36) PRIMARY KEY, ticket_number VARCHAR(32) NOT NULL UNIQUE,
 requester_id CHAR(36) NOT NULL, department_id CHAR(36) NOT NULL, assignee_id CHAR(36),
 title VARCHAR(200) NOT NULL, description TEXT NOT NULL, category VARCHAR(24) NOT NULL,
 priority VARCHAR(16) NOT NULL, status VARCHAR(24) NOT NULL, version BIGINT NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (requester_id) REFERENCES users(id), FOREIGN KEY (department_id) REFERENCES departments(id),
 FOREIGN KEY (assignee_id) REFERENCES users(id),
 CONSTRAINT ck_ticket_status CHECK (status IN ('OPEN','IN_PROGRESS','WAITING_USER','RESOLVED','CLOSED','CANCELLED')),
 CONSTRAINT ck_ticket_category CHECK (category IN ('IT','HR','FACILITIES','OTHER')),
 CONSTRAINT ck_ticket_priority CHECK (priority IN ('LOW','NORMAL','HIGH','URGENT')),
 INDEX ix_ticket_owner (requester_id,status,created_at,id),
 INDEX ix_ticket_department (department_id,status,created_at,id),
 INDEX ix_ticket_assignee (assignee_id,status,updated_at,id), INDEX ix_ticket_global (status,created_at,id)
) ENGINE=InnoDB;
CREATE TABLE ticket_comments (
 id CHAR(36) PRIMARY KEY, ticket_id CHAR(36) NOT NULL, author_id CHAR(36) NOT NULL,
 body TEXT NOT NULL, visibility VARCHAR(16) NOT NULL, origin VARCHAR(16) NOT NULL,
 created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (ticket_id) REFERENCES tickets(id), FOREIGN KEY (author_id) REFERENCES users(id),
 CONSTRAINT ck_comment_visibility CHECK (visibility IN ('PUBLIC','INTERNAL')),
 CONSTRAINT ck_comment_origin CHECK (origin IN ('HUMAN','AI_APPROVED')),
 INDEX ix_comment_ticket (ticket_id,visibility,created_at,id)
) ENGINE=InnoDB;
CREATE TABLE ticket_assignments (
 id CHAR(36) PRIMARY KEY, ticket_id CHAR(36) NOT NULL, from_assignee_id CHAR(36), to_assignee_id CHAR(36) NOT NULL,
 actor_id CHAR(36) NOT NULL, reason VARCHAR(1000), origin VARCHAR(16) NOT NULL, created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (ticket_id) REFERENCES tickets(id), FOREIGN KEY (from_assignee_id) REFERENCES users(id),
 FOREIGN KEY (to_assignee_id) REFERENCES users(id), FOREIGN KEY (actor_id) REFERENCES users(id),
 INDEX ix_assignment_ticket (ticket_id,created_at,id)
) ENGINE=InnoDB;
CREATE TABLE ticket_status_history (
 id CHAR(36) PRIMARY KEY, ticket_id CHAR(36) NOT NULL, from_status VARCHAR(24), to_status VARCHAR(24) NOT NULL,
 actor_id CHAR(36) NOT NULL, reason VARCHAR(2000), origin VARCHAR(16) NOT NULL, created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (ticket_id) REFERENCES tickets(id), FOREIGN KEY (actor_id) REFERENCES users(id),
 INDEX ix_status_ticket (ticket_id,created_at,id)
) ENGINE=InnoDB;

CREATE TABLE ai_conversations (
 id CHAR(36) PRIMARY KEY, owner_id CHAR(36) NOT NULL, title VARCHAR(200) NOT NULL,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (owner_id) REFERENCES users(id), INDEX ix_conversation_owner (owner_id,updated_at,id)
) ENGINE=InnoDB;
CREATE TABLE ai_messages (
 id CHAR(36) PRIMARY KEY, conversation_id CHAR(36) NOT NULL, turn_id CHAR(36) NOT NULL,
 role VARCHAR(16) NOT NULL, content MEDIUMTEXT NOT NULL, outcome VARCHAR(40) NOT NULL,
 provider VARCHAR(80), model_revision VARCHAR(200), prompt_tokens INT, completion_tokens INT, latency_ms INT,
 request_id VARCHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL,
 FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id), UNIQUE (conversation_id,turn_id,role),
 CONSTRAINT ck_message_role CHECK (role IN ('USER','ASSISTANT')),
 INDEX ix_message_conversation (conversation_id,created_at,id)
) ENGINE=InnoDB;
CREATE TABLE ai_message_citations (
 message_id CHAR(36) NOT NULL, citation_id VARCHAR(40) NOT NULL, chunk_id CHAR(36) NOT NULL,
 quote TEXT NOT NULL, PRIMARY KEY (message_id,citation_id),
 FOREIGN KEY (message_id) REFERENCES ai_messages(id), FOREIGN KEY (chunk_id) REFERENCES document_chunks(id)
) ENGINE=InnoDB;
CREATE TABLE ai_approvals (
 id CHAR(36) PRIMARY KEY, requester_id CHAR(36) NOT NULL, conversation_id CHAR(36) NOT NULL,
 turn_id CHAR(36) NOT NULL, tool_call_id CHAR(36) NOT NULL UNIQUE,
 tool_name VARCHAR(64) NOT NULL, tool_payload JSON NOT NULL, payload_hash CHAR(64) NOT NULL,
 evidence_chunk_ids JSON NOT NULL,
 target_ticket_id CHAR(36), expected_version BIGINT, risk_level VARCHAR(16) NOT NULL,
 status VARCHAR(16) NOT NULL, expires_at DATETIME(6) NOT NULL,
 approved_by CHAR(36), approved_at DATETIME(6), rejected_at DATETIME(6), decision_reason VARCHAR(1000),
 executed_at DATETIME(6), execution_result JSON,
 created_at DATETIME(6) NOT NULL, updated_at DATETIME(6) NOT NULL,
 FOREIGN KEY (requester_id) REFERENCES users(id), FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id),
 FOREIGN KEY (target_ticket_id) REFERENCES tickets(id), FOREIGN KEY (approved_by) REFERENCES users(id),
 CONSTRAINT ck_approval_status CHECK (status IN ('PENDING','APPROVED','REJECTED','EXECUTED','FAILED','EXPIRED')),
 CONSTRAINT ck_approval_risk CHECK (risk_level IN ('LOW','MEDIUM','HIGH')),
 CONSTRAINT ck_approval_self CHECK (approved_by IS NULL OR approved_by=requester_id),
 CONSTRAINT ck_approval_tool CHECK (tool_name IN ('createTicketDraft','assignTicketDraft','updateTicketStatusDraft','addTicketCommentDraft')),
 INDEX ix_approval_owner (requester_id,status,created_at,id), INDEX ix_approval_resume (status,expires_at,id)
) ENGINE=InnoDB;
CREATE TABLE ai_tool_executions (
 id CHAR(36) PRIMARY KEY, conversation_id CHAR(36) NOT NULL, turn_id CHAR(36) NOT NULL,
 tool_call_id CHAR(36) NOT NULL, phase VARCHAR(16) NOT NULL, approval_id CHAR(36) UNIQUE,
 actor_id CHAR(36) NOT NULL, tool_name VARCHAR(64) NOT NULL, payload_hash CHAR(64) NOT NULL,
 status VARCHAR(16) NOT NULL, result JSON, error_code VARCHAR(80), request_id VARCHAR(64) NOT NULL,
 started_at DATETIME(6) NOT NULL, finished_at DATETIME(6),
 FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id), FOREIGN KEY (approval_id) REFERENCES ai_approvals(id),
 FOREIGN KEY (actor_id) REFERENCES users(id), UNIQUE (tool_call_id,phase),
 CONSTRAINT ck_execution_phase CHECK (phase IN ('READ','DRAFT','EXECUTE')),
 CONSTRAINT ck_execution_status CHECK (status IN ('RUNNING','SUCCEEDED','FAILED')),
 INDEX ix_execution_conversation (conversation_id,started_at,id)
) ENGINE=InnoDB;
CREATE TABLE idempotency_records (
 actor_id CHAR(36) NOT NULL, operation VARCHAR(100) NOT NULL,
 idempotency_key VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 request_hash CHAR(64) NOT NULL, response_status INT NOT NULL, response_body JSON NOT NULL,
 created_at DATETIME(6) NOT NULL, expires_at DATETIME(6) NOT NULL,
 PRIMARY KEY (actor_id,operation,idempotency_key), FOREIGN KEY (actor_id) REFERENCES users(id),
 INDEX ix_idempotency_expiry (expires_at)
) ENGINE=InnoDB;
CREATE TABLE audit_logs (
 id CHAR(36) PRIMARY KEY, actor_id CHAR(36), actor_type VARCHAR(16) NOT NULL,
 action VARCHAR(80) NOT NULL, resource_type VARCHAR(64) NOT NULL, resource_id VARCHAR(64),
 outcome VARCHAR(16) NOT NULL, metadata JSON NOT NULL, request_id VARCHAR(64) NOT NULL,
 timestamp DATETIME(6) NOT NULL,
 FOREIGN KEY (actor_id) REFERENCES users(id),
 INDEX ix_audit_actor (actor_id,timestamp,id), INDEX ix_audit_resource (resource_type,resource_id,timestamp,id),
 INDEX ix_audit_request (request_id,timestamp), INDEX ix_audit_time (timestamp,id)
) ENGINE=InnoDB;
