<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { Plus, Setting } from '@element-plus/icons-vue'; import { ElMessage } from 'element-plus'
import { knowledgeApi } from '../../api/knowledge'; import type { ArticleStatus, KnowledgeArticle, KnowledgeCategory } from '../../types'; import { useAuthStore } from '../../stores/auth'; import { canManageKnowledge } from '../../utils/permissions'; import { apiErrorMessage } from '../../utils/errors'; import { displayLabel, formatDate, shortId } from '../../utils/format'; import PageHeading from '../../components/PageHeading.vue'; import StatusPill from '../../components/StatusPill.vue'; import EmptyState from '../../components/EmptyState.vue'
const auth=useAuthStore();const router=useRouter();const articles=ref<KnowledgeArticle[]>([]);const categories=ref<KnowledgeCategory[]>([]);const total=ref(0);const loading=ref(false);const categoryOpen=ref(false);const categorySaving=ref(false);const categoryForm=reactive({name:'',description:''});const filters=reactive<{page:number;size:number;status?:ArticleStatus;categoryId?:string}>({page:0,size:10});const manage=computed(()=>canManageKnowledge(auth.user));const categoryName=(id:string)=>categories.value.find(c=>c.id===id)?.name||shortId(id)
async function load(){loading.value=true;try{const [a,c]=await Promise.all([knowledgeApi.articles(filters),knowledgeApi.categories()]);articles.value=a.data.content;total.value=a.data.totalElements;categories.value=c.data}catch(e){ElMessage.error(apiErrorMessage(e))}finally{loading.value=false}}
async function createCategory(){if(!categoryForm.name.trim())return;categorySaving.value=true;try{await knowledgeApi.createCategory({name:categoryForm.name.trim(),description:categoryForm.description.trim()});ElMessage.success('分类已创建');categoryOpen.value=false;categoryForm.name='';categoryForm.description='';await load()}catch(e){ElMessage.error(apiErrorMessage(e))}finally{categorySaving.value=false}}
onMounted(load)
</script>
<template><div><PageHeading title="知识文章" description="沉淀并共享可靠指南，减少重复问题。"><el-button v-if="manage" @click="categoryOpen=true"><el-icon><Setting /></el-icon>分类管理</el-button><el-button v-if="manage" type="primary" @click="router.push('/knowledge/articles/new')"><el-icon><Plus /></el-icon>新建文章</el-button></PageHeading><section class="content-card"><div class="filter-bar"><el-select v-model="filters.categoryId" clearable placeholder="全部分类" @change="filters.page=0;load()"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id" /></el-select><el-select v-if="manage" v-model="filters.status" clearable placeholder="全部状态" @change="filters.page=0;load()"><el-option v-for="s in ['DRAFT','PUBLISHED','ARCHIVED']" :key="s" :value="s" :label="displayLabel(s)" /></el-select><span class="result-count">共 {{ total }} 篇文章</span></div><el-table v-loading="loading" :data="articles" class="data-table" @row-click="(row:KnowledgeArticle)=>router.push(`/knowledge/articles/${row.id}`)"><el-table-column label="文章" min-width="280"><template #default="{row}"><div class="primary-cell"><strong>{{ row.title }}</strong><code>{{ shortId(row.id) }}</code></div></template></el-table-column><el-table-column label="分类" min-width="160"><template #default="{row}">{{ categoryName(row.categoryId) }}</template></el-table-column><el-table-column label="状态" width="140"><template #default="{row}"><StatusPill :value="row.status" /></template></el-table-column><el-table-column label="作者" width="140"><template #default="{row}"><code>{{ shortId(row.authorId) }}</code></template></el-table-column><el-table-column label="更新时间" width="190"><template #default="{row}">{{ formatDate(row.updatedAt) }}</template></el-table-column><template #empty><EmptyState title="暂无文章" description="已发布的指南和你的草稿会显示在这里。" /></template></el-table><div class="pagination-row"><el-pagination :current-page="filters.page+1" :page-size="filters.size" :total="total" layout="prev, pager, next" @current-change="(page:number)=>{filters.page=page-1;load()}" /></div></section><el-dialog v-model="categoryOpen" title="新建分类" width="480px"><el-form label-position="top"><el-form-item label="名称"><el-input v-model="categoryForm.name" maxlength="100" placeholder="例如：IT 运维" /></el-form-item><el-form-item label="说明"><el-input v-model="categoryForm.description" type="textarea" :rows="3" maxlength="1000" /></el-form-item></el-form><template #footer><el-button @click="categoryOpen=false">取消</el-button><el-button type="primary" :loading="categorySaving" :disabled="!categoryForm.name.trim()" @click="createCategory">创建分类</el-button></template></el-dialog></div></template>
