<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';import { useRoute, useRouter } from 'vue-router';import { ElMessage, ElMessageBox } from 'element-plus'
import { knowledgeApi } from '../../api/knowledge';import type { KnowledgeArticle, KnowledgeCategory } from '../../types';import { useAuthStore } from '../../stores/auth';import { canManageKnowledge } from '../../utils/permissions';import { apiErrorMessage } from '../../utils/errors';import { formatDate, shortId } from '../../utils/format';import StatusPill from '../../components/StatusPill.vue'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const article=ref<KnowledgeArticle|null>(null);const categories=ref<KnowledgeCategory[]>([]);const loading=ref(true);const busy=ref(false);const manage=computed(()=>canManageKnowledge(auth.user));const category=computed(()=>categories.value.find(c=>c.id===article.value?.categoryId)?.name||'Uncategorized')
async function load(){loading.value=true;try{const [a,c]=await Promise.all([knowledgeApi.article(route.params.id as string),knowledgeApi.categories()]);article.value=a.data;categories.value=c.data}catch(e){ElMessage.error(apiErrorMessage(e));await router.replace('/knowledge/articles')}finally{loading.value=false}}
async function publish(){if(!article.value)return;busy.value=true;try{article.value=(await knowledgeApi.publishArticle(article.value.id,article.value.version)).data;ElMessage.success('Article published')}catch(e){ElMessage.error(apiErrorMessage(e));await load()}finally{busy.value=false}}
async function archive(){if(!article.value)return;try{await ElMessageBox.confirm('Archive this article? Employees will no longer be able to read it.','Archive article',{type:'warning',confirmButtonText:'Archive'});busy.value=true;article.value=(await knowledgeApi.archiveArticle(article.value.id,article.value.version)).data;ElMessage.success('Article archived')}catch(e){if(e!=='cancel')ElMessage.error(apiErrorMessage(e))}finally{busy.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><button class="back-link" @click="router.push('/knowledge/articles')">← Back to articles</button><article v-if="article" class="article-detail"><header><div class="detail-meta"><StatusPill :value="article.status" /><span>{{ category }}</span></div><h2>{{ article.title }}</h2><div class="article-byline">By <code>{{ shortId(article.authorId) }}</code> · Updated {{ formatDate(article.updatedAt) }} · Version {{ article.version }}</div><div v-if="manage" class="article-actions"><el-button v-if="article.status!=='ARCHIVED'" @click="router.push(`/knowledge/articles/${article.id}/edit`)">Edit</el-button><el-button v-if="article.status==='DRAFT'" type="primary" :loading="busy" @click="publish">Publish</el-button><el-button v-if="article.status!=='ARCHIVED'" type="danger" plain :loading="busy" @click="archive">Archive</el-button></div></header><section class="article-content">{{ article.content }}</section></article></div></template>
