<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';import { useRoute, useRouter } from 'vue-router';import { ElMessage, ElMessageBox } from 'element-plus'
import { knowledgeApi } from '../../api/knowledge';import type { KnowledgeArticle, KnowledgeCategory } from '../../types';import { useAuthStore } from '../../stores/auth';import { canManageKnowledge } from '../../utils/permissions';import { apiErrorMessage } from '../../utils/errors';import { formatDate, shortId } from '../../utils/format';import StatusPill from '../../components/StatusPill.vue'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const article=ref<KnowledgeArticle|null>(null);const categories=ref<KnowledgeCategory[]>([]);const loading=ref(true);const busy=ref(false);const manage=computed(()=>canManageKnowledge(auth.user));const category=computed(()=>categories.value.find(c=>c.id===article.value?.categoryId)?.name||'未分类')
async function load(){loading.value=true;try{const [a,c]=await Promise.all([knowledgeApi.article(route.params.id as string),knowledgeApi.categories()]);article.value=a.data;categories.value=c.data}catch(e){ElMessage.error(apiErrorMessage(e));await router.replace('/knowledge/articles')}finally{loading.value=false}}
async function publish(){if(!article.value)return;busy.value=true;try{article.value=(await knowledgeApi.publishArticle(article.value.id,article.value.version)).data;ElMessage.success('文章已发布')}catch(e){ElMessage.error(apiErrorMessage(e));await load()}finally{busy.value=false}}
async function archive(){if(!article.value)return;try{await ElMessageBox.confirm('归档后，普通员工将无法继续阅读这篇文章。确定归档吗？','归档文章',{type:'warning',confirmButtonText:'归档',cancelButtonText:'取消'});busy.value=true;article.value=(await knowledgeApi.archiveArticle(article.value.id,article.value.version)).data;ElMessage.success('文章已归档')}catch(e){if(e!=='cancel')ElMessage.error(apiErrorMessage(e))}finally{busy.value=false}}
onMounted(load)
</script>
<template><div v-loading="loading"><button class="back-link" @click="router.push('/knowledge/articles')">← 返回文章列表</button><article v-if="article" class="article-detail"><header><div class="detail-meta"><StatusPill :value="article.status" /><span>{{ category }}</span></div><h2>{{ article.title }}</h2><div class="article-byline">作者：<code>{{ shortId(article.authorId) }}</code> · 更新于 {{ formatDate(article.updatedAt) }} · 版本 {{ article.version }}</div><div v-if="manage" class="article-actions"><el-button v-if="article.status!=='ARCHIVED'" @click="router.push(`/knowledge/articles/${article.id}/edit`)">编辑</el-button><el-button v-if="article.status==='DRAFT'" type="primary" :loading="busy" @click="publish">发布</el-button><el-button v-if="article.status!=='ARCHIVED'" type="danger" plain :loading="busy" @click="archive">归档</el-button></div></header><section class="article-content">{{ article.content }}</section></article></div></template>
